/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-05-28 05:35:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.DExellent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("<!--         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" /> -->\r\n");
      out.write("    \t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>강아지는 훌륭하다</title>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"/assets/img/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"http://fonts.googleapis.com/earlyaccess/nanumbrushscript.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("          <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\" style=\"margin-left: 10px;\">\r\n");
      out.write("                    <img src=\"/assets/img/DEIMG/title.png\" width=\"50\" height=\"50\"/>\r\n");
      out.write("                    <div class=\"title\" style=\"display: inline; font-family: 'Nanum Brush Script', serif; margin-left: 5px;\">\r\n");
      out.write("                        \t\t강아지는 훌륭하다\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" style=\"font-family: 'Nanum Brush Script', serif; font-size: 20px;\">Menu<i class=\"fas fa-bars ml-1\"></i></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                    <ul class=\"navbar-nav text-uppercase ml-auto\">\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (session.getAttribute("user_name")==null) { 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\t\r\n");
      out.write("                    <a href=\"https://kauth.kakao.com/oauth/authorize?client_id=928bbb3f0e2b7934f85c85beaa13b7ea&redirect_uri=http://localhost:8080/kakaologin.do&response_type=code\">\r\n");
      out.write("        \t\t\t<img src=\"/assets/img/DEIMG/kakaologin.png\" style=\"width:260px; margin-left:40px; margin-top:10px;\">\r\n");
      out.write("\t\t\t\t    </a>\r\n");
      out.write(" \t\t\t\t    ");
 } else {  
      out.write("\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#services\">EMPATHY</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#portfolio\">YOUTUBE</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#about\">INFORMATION</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#team\">KINDERGARTEN</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#contact\">BOARD</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#mypage\">MYPAGE</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"/kakaologout.do\">LOGOUT</a></li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("        <header class=\"masthead\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               \r\n");
      out.write("                <div class=\"masthead-heading text-uppercase\">\r\n");
      out.write("                            강아지는");
      out.print("&nbsp&nbsp&nbsp&nbsp&nbsp");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("                ");
      out.print("&nbsp&nbsp&nbsp&nbsp&nbsp");
      out.write("훌륭하다</div>\r\n");
      out.write("                ");
 if (session.getAttribute("user_name")==null) { 
      out.write("\r\n");
      out.write("                <input type=\"button\" value=\"W E L C O M E\" class=\"btn btn-primary btn-xl text-uppercase js-scroll-trigger\" onclick=\"alert('먼저 로그인 해주세요')\">\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <a class=\"btn btn-primary btn-xl text-uppercase js-scroll-trigger\" href=\"#services\">W&nbspE&nbspL&nbspC&nbspO&nbspM&nbspE</a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        ");
 if (session.getAttribute("user_name")==null) { 
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("          <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-left\">Copyright © Your Website 2020</div>\r\n");
      out.write("                    <div class=\"col-lg-4 my-3 my-lg-0\">\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-right\"><a class=\"mr-3\" href=\"#!\">Privacy Policy</a><a href=\"#!\">Terms of Use</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Portfolio Modals--><!-- Modal 1-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/01-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Threads</li>\r\n");
      out.write("                                        <li>Category: Illustration</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 2-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/02-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Explore</li>\r\n");
      out.write("                                        <li>Category: Graphic Design</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 3-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/03-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Finish</li>\r\n");
      out.write("                                        <li>Category: Identity</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 4-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/04-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Lines</li>\r\n");
      out.write("                                        <li>Category: Branding</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 5-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/05-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Southwest</li>\r\n");
      out.write("                                        <li>Category: Website Design</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 6-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/06-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Window</li>\r\n");
      out.write("                                        <li>Category: Photography</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Third party plugin JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("        <!-- Contact form JS-->\r\n");
      out.write("        <script src=\"/assets/mail/jqBootstrapValidation.js\"></script>\r\n");
      out.write("        <script src=\"/assets/mail/contact_me.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"/js/scripts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t<!-- Services-->\r\n");
      out.write("        <hr style=\"margin-top: 50px;\">\r\n");
      out.write("        <section class=\"page-section\" id=\"services\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">EMPATHY</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Animal empathy for dog owners.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("              \t<div src=\"/empathy.do\">\r\n");
      out.write("              \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Portfolio Grid-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">YOUTUBE</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">YouTube Related to Puppies.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal1\"\r\n");
      out.write("                                ><div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"/assets/img/portfolio/01-thumbnail.jpg\" alt=\"\"\r\n");
      out.write("                            /></a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Threads</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Illustration</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal2\"\r\n");
      out.write("                                ><div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"/assets/img/portfolio/02-thumbnail.jpg\" alt=\"\"\r\n");
      out.write("                            /></a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Explore</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Graphic Design</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal3\"\r\n");
      out.write("                                ><div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"/assets/img/portfolio/03-thumbnail.jpg\" alt=\"\"\r\n");
      out.write("                            /></a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Finish</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Identity</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-lg-0\">\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal4\"\r\n");
      out.write("                                ><div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"/assets/img/portfolio/04-thumbnail.jpg\" alt=\"\"\r\n");
      out.write("                            /></a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Lines</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Branding</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-sm-0\">\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal5\"\r\n");
      out.write("                                ><div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"/assets/img/portfolio/05-thumbnail.jpg\" alt=\"\"\r\n");
      out.write("                            /></a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Southwest</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Website Design</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"portfolio-item\">\r\n");
      out.write("                            <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal6\"\r\n");
      out.write("                                ><div class=\"portfolio-hover\">\r\n");
      out.write("                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img class=\"img-fluid\" src=\"/assets/img/portfolio/06-thumbnail.jpg\" alt=\"\"\r\n");
      out.write("                            /></a>\r\n");
      out.write("                            <div class=\"portfolio-caption\">\r\n");
      out.write("                                <div class=\"portfolio-caption-heading\">Window</div>\r\n");
      out.write("                                <div class=\"portfolio-caption-subheading text-muted\">Photography</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- About-->\r\n");
      out.write("        <section class=\"page-section\" id=\"about\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">INFORMATION</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">puppy-related information.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"timeline\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"/assets/img/about/1.jpg\" alt=\"\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>2009-2011</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Our Humble Beginnings</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"/assets/img/about/2.jpg\" alt=\"\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>March 2011</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">An Agency is Born</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"/assets/img/about/3.jpg\" alt=\"\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>December 2012</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Transition to Full Service</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\"><img class=\"rounded-circle img-fluid\" src=\"/assets/img/about/4.jpg\" alt=\"\" /></div>\r\n");
      out.write("                        <div class=\"timeline-panel\">\r\n");
      out.write("                            <div class=\"timeline-heading\">\r\n");
      out.write("                                <h4>July 2014</h4>\r\n");
      out.write("                                <h4 class=\"subheading\">Phase Two Expansion</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"timeline-body\"><p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"timeline-inverted\">\r\n");
      out.write("                        <div class=\"timeline-image\">\r\n");
      out.write("                            <h4>Be Part<br />Of Our<br />Story!</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Team-->\r\n");
      out.write("        <section class=\"page-section bg-light\" id=\"team\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">KINDERGARTEN</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Provides location for puppy kindergartens.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"/assets/img/team/1.jpg\" alt=\"\" />\r\n");
      out.write("                            <h4>Kay Garland</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Designer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"/assets/img/team/2.jpg\" alt=\"\" />\r\n");
      out.write("                            <h4>Larry Parker</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Marketer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"team-member\">\r\n");
      out.write("                            <img class=\"mx-auto rounded-circle\" src=\"/assets/img/team/3.jpg\" alt=\"\" />\r\n");
      out.write("                            <h4>Diana Petersen</h4>\r\n");
      out.write("                            <p class=\"text-muted\">Lead Developer</p>\r\n");
      out.write("                            <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 mx-auto text-center\"><p class=\"large text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Clients-->\r\n");
      out.write("        <section class=\"py-5\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/logos/envato.jpg\" alt=\"\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/logos/designmodo.jpg\" alt=\"\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/logos/themeforest.jpg\" alt=\"\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 my-3\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/logos/creative-market.jpg\" alt=\"\" /></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Contact-->\r\n");
      out.write("        <section class=\"page-section\" id=\"contact\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">BOARD</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Feel free to share your opinions.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form id=\"contactForm\" name=\"sentMessage\" novalidate=\"novalidate\">\r\n");
      out.write("                    <div class=\"row align-items-stretch mb-5\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Your Name *\" required=\"required\" data-validation-required-message=\"Please enter your name.\" />\r\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Your Email *\" required=\"required\" data-validation-required-message=\"Please enter your email address.\" />\r\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group mb-md-0\">\r\n");
      out.write("                                <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Your Phone *\" required=\"required\" data-validation-required-message=\"Please enter your phone number.\" />\r\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group form-group-textarea mb-md-0\">\r\n");
      out.write("                                <textarea class=\"form-control\" id=\"message\" placeholder=\"Your Message *\" required=\"required\" data-validation-required-message=\"Please enter a message.\"></textarea>\r\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                        <div id=\"success\"></div>\r\n");
      out.write("                        <button class=\"btn btn-primary btn-xl text-uppercase\" id=\"sendMessageButton\" type=\"submit\">Send Message</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- mypage-->\r\n");
      out.write("        <section class=\"page-section\" id=\"mypage\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"section-heading text-uppercase\">MYPAGE</h2>\r\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Displays Kakao member information.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <iframe src=\"/DExellent/mypage.do\" width=\"100%\" height=\"750px\" name=\"mypage1\" id=\"mypage1\"></iframe> \r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-left\">Copyright © Your Website 2020</div>\r\n");
      out.write("                    <div class=\"col-lg-4 my-3 my-lg-0\">\r\n");
      out.write("                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a><a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 text-lg-right\"><a class=\"mr-3\" href=\"#!\">Privacy Policy</a><a href=\"#!\">Terms of Use</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Portfolio Modals--><!-- Modal 1-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/01-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Threads</li>\r\n");
      out.write("                                        <li>Category: Illustration</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 2-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/02-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Explore</li>\r\n");
      out.write("                                        <li>Category: Graphic Design</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 3-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/03-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Finish</li>\r\n");
      out.write("                                        <li>Category: Identity</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 4-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/04-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Lines</li>\r\n");
      out.write("                                        <li>Category: Branding</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 5-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/05-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Southwest</li>\r\n");
      out.write("                                        <li>Category: Website Design</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal 6-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"close-modal\" data-dismiss=\"modal\"><img src=\"/assets/img/close-icon.svg\" /></div>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <!-- Project Details Go Here-->\r\n");
      out.write("                                    <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                                    <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                                    <img class=\"img-fluid d-block mx-auto\" src=\"/assets/img/portfolio/06-full.jpg\" alt=\"\" />\r\n");
      out.write("                                    <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                                    <ul class=\"list-inline\">\r\n");
      out.write("                                        <li>Date: January 2020</li>\r\n");
      out.write("                                        <li>Client: Window</li>\r\n");
      out.write("                                        <li>Category: Photography</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-times mr-1\"></i>Close Project</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Third party plugin JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("        <!-- Contact form JS-->\r\n");
      out.write("        <script src=\"/assets/mail/jqBootstrapValidation.js\"></script>\r\n");
      out.write("        <script src=\"/assets/mail/contact_me.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"/js/scripts.js\"></script>\r\n");
      out.write("</html>\r\n");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
